### ISSUE TITLE
Always the same picture

### ISSUE THREAD

**Issue by koarlmichael** [jancborchardt/unsplash#38]
The background does not change anymore. It always shows the same picture. Even if the URL is entered manually: https://source.unsplash.com/random/featured/?nature

**Comment by marius-wieschollek** [comment]
I seems like the image is now cached by unsplash for some time.

**Comment by helio4k** [comment]
I can concur I have the same issues of lately

**Comment by marius-wieschollek** [comment]
This is a change made by unsplash, not by us. We can not do anything about this.

**Comment by jancborchardt** [comment]
On the positive side, it sort of resolves these issues:
- background image should be cached until a login process has been finshed #2 (opened by @j-ed)
- Request: Pull image(s) in advance with cronjob to have it ready uppon loading the page #7 (opened by @konstantinwall)
- Use daily or weekly images instead of random #19 (opened by @milosz)

:wink:

**Comment by marius-wieschollek** [comment]
For me the behaviour changed again. I am now getting a redirect to a different picture each time.

**Comment by newhinton** [comment]
@koarlmichael Is this issue maybe related to #40? Can this be closed?

**Comment by koarlmichael** [comment]
> @koarlmichael Is this issue maybe related to #40? Can this be closed?

Yes I think so, thanks!
